[package]
name = "aoc202007"
version = "0.1.0"
authors = ["Toby Oxborrow <tobyox@cisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5"
regex = "1"
lazy_static = "1.4.0"
itertools = "0.9"
