[package]
name = "aoc202004"
version = "0.1.0"
authors = ["Toby Oxborrow <toby@oxborrow.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
